source: source/index.js
dist: test/CompareProducts.js

bfPlugins:
  - name: watchify
  - name: errorify

bfTransforms:
  - name: eslintify
    options:
      passthrough: [ 'errors', 'warnings' ]
  - name: jstify
    options:
      engine: global
  - name: nocommentify

proxy:
  https: false
  serveStatic: ['.']
  rewriteRules:
    - match: !!js/regexp /https://assets3.insales.ru/assets/\d{1,}/\d{1,}/\d{1,}/v_\d{1,}/build/CompareProducts.js/
      replace: /test/CompareProducts.js
